### PR TITLE
Display likes

### PR DESCRIPTION
**Pull request by awais-amjed**
In this PR, the following changes were introduced:

- Implemented functions for posting a like and getting all likes.
- Displayed the number of likes in the Jokes Card for every item.
- Fixed Header on Mobile Screens.

image

### CODE REVIEW

**Review by Bavon101 — COMMENTED** [review]
hello @awais-amjed ,
Your changes are remarkably greater,

- [x] Your commits are great 
- [x] The UI is nice
- [x] The code is clean
I just found some minor issue or just a bad misplaced `like button`, how does one like a joke? 
I've tried looking but only the likes counts are displayed, without an original action.

- Please do add a like Icon or button for a user to be able to initiate their likes count.
giggy_like

**Comment by awais-amjed** [comment]
@Bavon101 Thanks for the review, The Like button is not a part of this PR, it's the part of the next PR. You can check that in the Kanban Board.

**Comment by Bavon101** [comment]
> @Bavon101 Thanks for the review, The Like button is not a part of this PR, it's the part of the next PR. You can check that in the Kanban Board.

Noted @awais-amjed , Sorry for the misunderstanding.

**Comment by awais-amjed** [comment]
> 

No Problem @Bavon101 . Can you please approve the PR, Thanks.

**Review by Bavon101 — APPROVED** [review]
Hello @awais-amjed ,
Your project meets all the changes in scope.✔
Great work, I give a  green light for a merge.

**Pull request merged**
